# Dependabot will run on day 4 of each month at 01:30 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "30 1 4 * *"
    open-pull-requests-limit: 15
  - package-ecosystem: "npm"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "30 1 4 * *"
    open-pull-requests-limit: 20
    versioning-strategy: "increase"
    directories: "**/*"
